Mox.defmock(Lastfm.ClientMock, for: Lastfm.Client)
Mox.defmock(Lastfm.FileArchiveMock, for: Lastfm.Archive)
Mox.defmock(Lastfm.FileIOMock, for: Lastfm.FileIO)
Mox.defmock(Lastfm.PathIOMock, for: Lastfm.PathIO)
Mox.defmock(LastfmArchive.CacheMock, for: LastfmArchive.Cache)
